import type { Metadata } from "next";
import "@/scss/globals.scss";
import "@/scss/normalize.scss";
import Header from "@/components/header/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { FavCountProvider } from "@/context/FavCountProvider";
import {
  PendingCountProvider,
  usePendingCount,
} from "@/context/PendingCountProvider";
import { auth } from "@clerk/nextjs/server";
import { NotificationCountProvider } from "@/context/NotificationCountProvider";

export const metadata: Metadata = {
  title: "hawwel",
  description: "Generated by hawwel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ClerkProvider>
          <NotificationCountProvider>
            <PendingCountProvider>
              <FavCountProvider>
                <Header />
                {children}
              </FavCountProvider>
            </PendingCountProvider>
          </NotificationCountProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
