import type { Metadata } from "next";
import "@/scss/globals.scss";
import "@/scss/normalize.scss";
import Header from "@/components/header/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { FavCountProvider } from "@/context/FavCountProvider";
import {
  PendingCountProvider,
  usePendingCount,
} from "@/context/PendingCountProvider";
import { auth } from "@clerk/nextjs/server";
import { NotificationCountProvider } from "@/context/NotificationCountProvider";
import PageTransition from "@/components/PageTransition/PageTransition";

export const metadata: Metadata = {
  title: "hawwel",
  description: "Generated by hawwel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark-theme');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body suppressHydrationWarning>
        <ClerkProvider>
          <NotificationCountProvider>
            <PendingCountProvider>
              <FavCountProvider>
                <Header />
                <PageTransition>{children}</PageTransition>
              </FavCountProvider>
            </PendingCountProvider>
          </NotificationCountProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
